context:
  name: sprocket
  version: "0.15.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/stjude-rust-labs/sprocket/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7144f195cb163a7145f8b2645241c645eba954722d292a3e574c59dea4a384a3

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - if: unix
      then:
        - export OPENSSL_DIR=${{ PREFIX }}
    - cargo install --locked --bins --no-track --root ${{ PREFIX }} --path .
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }} >= 1.82
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - sprocket help

about:
  homepage: https://sprocket.bio/
  summary: 'A bioinformatics workflow engine built on top of the Workflow Description Language (WDL).'
  description: |
    Sprocket is an bioinformatics workflow execution engine built on top of the Workflow Description Language.
    The project has multiple high-level goals, including to:

    - Provide a high-performance workflow execution engine capable of orchestrating massive bioinformatics workloads (the stated target is 20,000+ concurrent jobs).
    - Develop a suite of modern development tools that brings bioinformatics development on par with other modern languages (e.g., wdl-lsp).
    - Maintain an community-focused codebase that enables a diverse set of contributors from academic, non-profit, and commercial organizations.
    - Build on an open, domain-tailored standard to ensure the toolset remains singularly focused on unencumbered innovation within bioinformatics.
    - Retain a simple and accessible user experience when complexity isn't warranted.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  documentation: https://sprocket.bio/overview.html
  repository: https://github.com/stjude-rust-labs/sprocket

extra:
  recipe-maintainers:
    - luizirber
